//Motorola Shelter Stability Test 58 - Shelter Device B - Make a phone call
//Subroutine B1 - Receive Incoming Call from Shelter Device A
//Motorola Shelter Stability Test 59 - Switch from the telephony app to another app
//Tests are grouped together due to dependencies in functionality
//Completed 6-10-2013

run ClassUtilities.ConfirmTextOnScreen("INCOMING CALL")
run ClassUtilities.ConfirmTextOnScreen("SHELTERA")
run ClassUtilities.ConfirmTextOnScreen("MOBILE")
run ClassNavigate.AnswerCall
run ClassUtilities.ConfirmTextOnScreen("SHELTERA")
run ClassUtilities.ConfirmTextOnScreen("MOBILE")

//Motorola Shelter Stability Test 59 - Switch from the telephony app to another app
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/Taskbar/PhoneAppInBackground")
run ClassNavigate.OpenTaskbar
wait 1 second
Click (Text:"VNC Server")
run ClassUtilities.ConfirmTextOnScreen("Server is running")
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/Taskbar/PhoneAppInBackground")
Click "Device/AppIcons/TelephoneApp"
run ClassUtilities.ConfirmImageOnScreen("Device/System/Taskbar/PhoneAppInBackground")
Click (Text:"Return to call")

//Motorola Shelter Stability Test 60 - End the phone call
Click "Device/Apps/Telephone/EndCall"
run ClassUtilities.ConfirmImageNotOnScreen("Device/Apps/Telephone/EndCall")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/HistoryIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/PhoneIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/ContactsIcon")
run ClassUtilities.ConfirmImageNotOnScreen("Device/System/Taskbar/PhoneAppInBackground")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds