//Motorola Shelter Stability Test 50 - Record an Audio Message
//Motorola Shelter Stability Test 51 - Listen to an Audio Message
//Motorola Shelter Stability Test 52 - Delete an Audio Message
//Tests are grouped together due to dependencies in functionality
//Completed 5-23-2013

//Setup
run ClassNavigate.ResetState

//Test 50 - Record an Audio Message
run ClassNavigate.OpenApp(Recorder)
wait 2 seconds
run ClassUtilities.ConfirmTextOnScreen("Record your message")
Click (135,750)
run ClassUtilities.ConfirmTextOnScreen("Recording")
wait 4 seconds
Click (345, 750)
run ClassUtilities.ConfirmTextOnScreen("Message Recorded")
run ClassUtilities.ConfirmTextOnScreen(":05")

//Test 51 - Listen to an Audio Message
Click (240, 750)
run ClassUtilities.ConfirmTextOnScreen("Review message")

//Test 52 - Delete an Audio Message
Click (Text:"Discard")
run ClassUtilities.ConfirmTextOnScreen("Recorder")

//Teardown
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds
