//Motorola Shelter Stability Test 02 -- Make a 3G voice call from the phone book
//Component of Script Series 02
//Completed 6-10-2013

//Subroutine A2 -- Shelter Device A - Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/HistoryIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/PhoneIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/ContactsIcon")
Click "Device/Apps/Telephone/HistoryIcon"
run ClassUtilities.ConfirmTextInArea(universal firstnamedeviceb),("10,100"),("450,225")
run ClassUtilities.ConfirmImageOnScreen(ImageName:"Device/Apps/Telephone/0MinsAgo",   SearchRectangle:((10,100),(450,225)))
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds