//Motorola Shelter Stability Test 04 - Make a 2G voice call from the call history list
//Component of Script Series 04
//Completed 6-10-2013

//Subroutine B1 - Shelter Device B - Receive Incoming Call from Shelter Device A
run ClassUtilities.ConfirmTextOnScreen("INCOMING CALL")
run ClassUtilities.ConfirmTextOnScreen("SHELTERA")
run ClassUtilities.ConfirmTextOnScreen("MOBILE")
run ClassNavigate.AnswerCall
run ClassUtilities.ConfirmTextOnScreen("SHELTERA")
run ClassUtilities.ConfirmTextOnScreen("MOBILE")
Click "Device/Apps/Telephone/EndCall"
run ClassUtilities.ConfirmImageNotOnScreen("Device/Apps/Telephone/EndCall")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/HistoryIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/PhoneIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/ContactsIcon")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds