//Motorola Shelter Stability Test 50 - Record an Audio Message
//Motorola Shelter Stability Test 51 - Listen to an Audio Message
//Motorola Shelter Stability Test 52 - Delete an Audio Message
//Tests are grouped together due to dependencies in functionality
//Completed 5-23-2013
//Current for build 1.25

//Setup
run ClassNavigate.ResetState

//Test 50 - Record an Audio Message
run ClassNavigate.OpenApp(Recorder)
wait 5 seconds
run ClassUtilities.ConfirmTextInArea("Record your message"),("50,30"),("450,100")
Click (135,750)
run ClassUtilities.ConfirmTextOnScreen("Recording")
wait 4 seconds
Click (345, 750)
run ClassUtilities.ConfirmTextInArea("Message Recorded"),("50,30"),("450,100")

//Test 51 - Listen to an Audio Message
Click (240, 750)
run ClassUtilities.ConfirmTextInArea("Review message"),("50,30"),("450,100")

//Test 52 - Delete an Audio Message
Click (Text:"Discard")
run ClassUtilities.ConfirmTextOnScreen("Recorder")

//Teardown
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds
