//Motorola Shelter Stability Test 04 -- Make a 2G voice call from the call history list
//Component of Script Series 04
//Completed 6-10-2013

//Subroutine A2 -- Shelter Device A - Set mobile networks to default
Click "Device/System/Backicon"
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/HistoryIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/PhoneIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/ContactsIcon")
Click "Device/Apps/Telephone/HistoryIcon"
run ClassUtilities.ConfirmTextInArea(universal firstnamedeviceb),("10,100"),("450,225")
run ClassUtilities.ConfirmImageOnScreen(ImageName:"Device/Apps/Telephone/0MinsAgo",   SearchRectangle:((10,100),(450,225)))
Log "Phone call data confirmed."
Click "Device/System/HomeButton"
run ClassNavigate.OpenApp(Settings)
run ClassNavigate.SettingsOption(More)
Click (Text:"Mobile networks")
run ClassConfigure.Set2Gnetwork(Off)
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds