//Motorola Shelter Stability Test 38 - Set an alarm
//Motorola Shelter Stability Test 40 - Delete an alarm
//Tests are grouped together due to dependencies in functionality
//Completed 5-22-2013
//Current for build 1.25

//Setup
//Confirms 2 default off alarms are present
run ClassNavigate.ResetState
run ClassNavigate.OpenApp(Clock)
wait 1 second
Click (Text:"Set alarm")
wait 1 second
run ClassUtilities.ConfirmTextOnScreen("8:30 AM")
run ClassUtilities.ConfirmTextOnScreen("9:00 AM")
Click "Device/System/HomeButton"

//Test 38 - Set an alarm
run ClassNavigate.OpenApp(Clock)
wait 1 second
Click (Text:"Set alarm")
wait 1 second
Click "Device/Apps/Clock/AddAlarm"
Click (Text:"Turn alarm on")
Click (Text:"DONE")
wait 1 second
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Settings/CheckboxSelected")
run ClassUtilities.ConfirmImageOnScreen("Device/System/Taskbar/AlarmActive")

//Test 40 - Delete an alarm
Click(140,390)
Click "Device/AppIcons/TrashcanIcon"
run ClassUtilities.ConfirmTextOnScreen("Delete this alarm?")
Click(Text:"OK")
wait 1 second
run ClassUtilities.ConfirmImageNotOnScreen("Device/System/Taskbar/AlarmActive")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds









