//Motorola Shelter Stability Test 04 -- Make a 2G voice call from the call history list
//Component of Script Series 04
//Completed 6-10-2013

//Subroutine B2 -- Shelter Device B - Receive Incoming Call from Shelter Device A
WaitFor 30, Text:"INCOMING CALL", CaseSensitive: true
run ClassUtilities.ConfirmTextOnScreen(universal firstnamedevicea)
run ClassUtilities.ConfirmTextOnScreen("MOBILE")
run ClassNavigate.AnswerCall
run ClassUtilities.ConfirmTextOnScreen(universal firstnamedevicea)
run ClassUtilities.ConfirmTextOnScreen("MOBILE")
Log "Terminating phone call."
Click "Device/Apps/Telephone/EndCall"
wait 2 seconds
run ClassUtilities.ConfirmImageNotOnScreen("Device/Apps/Telephone/EndCall")
Click "Device/AppIcons/TelephoneApp"
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/HistoryIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/PhoneIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/ContactsIcon")
Click "Device/Apps/Telephone/HistoryIcon"
run ClassUtilities.ConfirmTextInArea(universal firstnamedevicea),("10,100"),("450,225")
run ClassUtilities.ConfirmImageOnScreen(ImageName:"Device/Apps/Telephone/0MinsAgo",   SearchRectangle:((10,100),(450,225)))
Log "Phone call data confirmed."
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")