//Motorola Shelter Stability Test 12 -- Send a MMS with a 1MB video attachment or largest size supported by the device
//Component of Script Series 12
//Completed 6-12-2013

//Setup
run ClassNavigate.ResetState

//Subroutine A1 -- Shelter Device A - Send 1MB video MMS to Shelter Device B
//French language is used to identify this tested functionality
Click "Device/AppIcons/MessagingApp"
run ClassUtilities.ConfirmTextOnScreen("Messaging")
Click "Device/Apps/Messaging/NewMessageIcon"
wait 1 second
Click (Text:"To")
TypeText "S"
wait 1 second
Click (Text:"ShelterB")
run ClassUtilities.ConfirmTextInArea("ShelterB DeviceB"),("10,100"),("450,200")
Click (Text:"Type message")
wait 1 second
TypeText "Portez ce vieux whisky au juge blond qui fume. "
wait 3 seconds
run ClassUtilities.ConfirmTextInArea("Portez ce vieux whisky"),("10,315"),("470,425")
run ClassUtilities.ConfirmTextInArea("blond qui fume"),("10,315"),("470,425")
Click "Device/Apps/Messaging/AttachmentIcon"
Click "Device/Apps/Messaging/VideoAttachment"
wait 2 seconds
Click (240,400)
wait 2 seconds
Click (240,400)
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Messaging/VideoAttachmentSample1b")
run ClassUtilities.ConfirmTextInArea("MMS"),("375,700"),("470,765")
run ClassUtilities.ConfirmTextInArea("Portez ce vieux whisky"),("10,700"),("470,800")
run ClassUtilities.ConfirmTextInArea("blond qui fume"),("10,700"),("470,800")
Click "Device/Apps/Messaging/SendMessage"
wait 20 seconds
Click (460,700)
wait 1 second
run ClassUtilities.ConfirmTextInArea("ideo Attachment"),("0,500"),("470,750")
run ClassUtilities.ConfirmTextInArea("mp4"),("0,500"),("470,750")
run ClassUtilities.ConfirmTextInArea("Portez ce vieux whisky"),("1,500"),("470,750")
run ClassUtilities.ConfirmTextInArea("blond qui fume"),("1,500"),("470,750")
run ClassUtilities.ConfirmTextOnScreen("Type message")
Click "Device/System/BackIcon"
wait 1 second
run ClassUtilities.ConfirmTextOnScreen("Messaging")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds