//Motorola Shelter Stability Test 18 -- Send an email with no attachment
//Component of Script Series 18
//Completed 6-12-2013

//Setup
run ClassNavigate.ResetState

//Subroutine A1 -- Shelter Device A - Send an email with no attachment to Shelter Device B
wait 10 seconds
run ClassNavigate.OpenApp(Email)
run ClassConfigure.ResetEmail
Click "Device/Apps/Email/ComposeEmail"
wait 1 second
TypeText "sh"
wait 1 second
Click (Text:"ShelterB")
run ClassUtilities.ConfirmTextInArea("ShelterB DeviceB"),("10,175"),("450,275")
Click (Text:"Subject")
TypeText "Test email no attachment"
run ClassUtilities.ConfirmTextInArea("Test email no attachment"),("10,250"),("450,350")
Click (Text:"Compose email")
TypeText "Sent from ShelterA."
run ClassUtilities.ConfirmTextInArea("Sent from ShelterA"),("10,350"),("450,450")
Click "Device/Apps/Email/SendEmail"
wait 1 second
run ClassUtilities.ConfirmTextOnScreen("Inbox")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds