//Motorola Shelter Stability Test 11 - Send a MMS with a 1MB audio attachment or largest size supported by the device
//Component of Script Series 11
//Completed 6-12-2013

//Setup
run ClassNavigate.ResetState

//Subroutine A1 - Shelter Device A - Send 1MB Audio MMS to Shelter Device B
Click "Device/AppIcons/MessagingApp"
run ClassUtilities.ConfirmTextOnScreen("Messaging")
Click "Device/Apps/Messaging/NewMessageIcon"
wait 1 second
Click (Text:"To")
TypeText "S"
wait 1 second
Click (Text:"ShelterB")
run ClassUtilities.ConfirmTextInArea("ShelterB DeviceB"),("10,100"),("450,200")
Click (Text:"Type message")
wait 1 second
TypeText "Victor jagt zwolf Boxkampfer quer uber den grossen Sylter Deich. "
wait 3 seconds
run ClassUtilities.ConfirmTextInArea("Victor"),("10,315"),("470,425")
run ClassUtilities.ConfirmTextInArea("uber den"),("10,315"),("470,425")
Click "Device/Apps/Messaging/AttachmentIcon"
Click "Device/Apps/Messaging/AudioAttachment"
Click (Text:"music track")
Click (Text:"Audio Attachment")
Click (Text:"OK", SearchRectangle:((10,700),(200,800)))
run ClassUtilities.ConfirmTextInArea("Audio Attachment"),("25,550"),("325,650")
run ClassUtilities.ConfirmTextInArea("Music"),("25,550"),("325,650")
run ClassUtilities.ConfirmTextInArea("MMS"),("375,700"),("470,765")
run ClassUtilities.ConfirmTextInArea("Victor"),("10,700"),("470,800")
run ClassUtilities.ConfirmTextInArea("uber den"),("10,700"),("470,800")
Click "Device/Apps/Messaging/SendMessage"
wait 20 seconds
Click (460,700)
wait 1 second
run ClassUtilities.ConfirmTextInArea("Audio Attachment"),("1,500"),("470,750")
run ClassUtilities.ConfirmTextInArea("Victor jagt zwolf Boxkampfer"),("1,500"),("470,750")
run ClassUtilities.ConfirmTextInArea("quer uber den grossen"),("1,500"),("470,750")
run ClassUtilities.ConfirmTextOnScreen("Type message")
Click "Device/System/BackIcon"
wait 1 second
run ClassUtilities.ConfirmTextOnScreen("Messaging")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds