//Motorola Shelter Stability Test 09 - Add a contact to the phone book
//Motorola Shelter Stability Test 08 - Delete a contact from the phone book
//Tests are grouped together due to dependencies in functionality
//Completed 5-22-2013
//Current for build 1.25

//Setup
run ClassNavigate.ResetState

//Test 09 - Add a contact to the phone book
run ClassNavigate.OpenApp(People)
Click "Device/Apps/People/Contacts"
Click "Device/Apps/People/AddContact"
run ClassUtilities.IfTextOnScreen("Your new contact"),("OK") //Popup may appear
Click (Text:"First Name")
wait 1 second
TypeText "Pat"
Click (Text:"Last Name")
wait 1 second
TypeText "Riley"
Click (Text:"organization")
TypeText "Motorola"
Click (Text:"DONE", SearchRectangle:((5,50),(470,150)))
run ClassUtilities.ConfirmTextOnScreen("Pat Riley")
Click (Text:"Pat Riley")
run ClassUtilities.ConfirmTextOnScreen("Pat Riley")

//Test 08 - Delete a contact from the phone book
run ClassConfigure.DeleteContact("Pat Riley")
run ClassUtilities.ConfirmTextNotOnScreen(name)
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds
