//Motorola Shelter Stability Test 13 - Send a MMS with a 1MB image attachment or largest size supported by the device
//Component of Script Series 13
//Completed 6-12-2013

//Setup
run ClassNavigate.ResetState

//Subroutine A1 - Shelter Device A - Send 1MB image MMS to Shelter Device B
Click "Device/AppIcons/MessagingApp"
run ClassUtilities.ConfirmTextOnScreen("Messaging")
Click "Device/Apps/Messaging/NewMessageIcon"
wait 1 second
Click (Text:"To")
TypeText "S"
wait 1 second
Click (Text:"ShelterB")
run ClassUtilities.ConfirmTextInArea("ShelterB DeviceB"),("10,100"),("450,200")
Click (Text:"Type message")
wait 1 second
TypeText "El veloz murcielago hindu comia feliz cardillo y kiwi. "
wait 3 seconds
run ClassUtilities.ConfirmTextInArea("El veloz"),("10,315"),("470,425")
run ClassUtilities.ConfirmTextInArea("comia feliz cardillo"),("10,315"),("470,425")
Click "Device/Apps/Messaging/AttachmentIcon"
Click "Device/Apps/Messaging/ImageAttachment"
Click (Text:"Pictures")
wait 1 second
Click "Device/Apps/Messaging/ImageAttachmentSample1a"
wait 1 second
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Messaging/ImageAttachmentSample1b")
run ClassUtilities.ConfirmTextInArea("MMS"),("375,700"),("470,765")
run ClassUtilities.ConfirmTextInArea("El veloz"),("10,700"),("470,800")
run ClassUtilities.ConfirmTextInArea("comia feliz cardillo"),("10,700"),("470,800")
Click "Device/Apps/Messaging/SendMessage"
wait 10 seconds
Click (460,700)
wait 1 second
run ClassUtilities.ConfirmTextInArea("Attachment.jpg"),("0,500"),("470,750")
run ClassUtilities.ConfirmTextInArea("El veloz"),("1,500"),("470,750")
run ClassUtilities.ConfirmTextInArea("comia feliz cardillo"),("1,500"),("470,750")
run ClassUtilities.ConfirmTextOnScreen("Type message")
Click "Device/System/BackIcon"
wait 1 second
run ClassUtilities.ConfirmTextOnScreen("Messaging")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds