//Motorola Shelter Stability Test 53 - Play video streaming content using device browser and video player
//Motorola clarified that test should utilize youtube.com in browser for video streaming.  Video player unnecessary.
//Completed 6-04-2013

//Setup
run ClassNavigate.ResetState

//Test 53 - Play video streaming content using device browser
Click "Device/Apps/Browser/BrowserIcon"
//run ClassNavigate.OpenApp(Browser) [Alternate open method]
run ClassConfigure.SetBrowserHomepageToDefault
run ClassNavigate.GoToBrowserAddress("m.youtube.com/watch?v=lcJuZIUeBME")
run ClassUtilities.ConfirmTextOnScreen("Canon in D Major")
Click (240,250)
wait 5 seconds
run ClassUtilities.ConfirmImageNotOnScreen("Device/Apps/Browser/Sites/YTubeBlackScreenVideo")
//insert commands for confirm background image here
run ClassUtilities.ConfirmImageNotOnScreen("Device/Apps/Browser/Sites/YTubeFullscreenButton")
run ClassConfigure.CloseAllBrowserTabs
Click "Device/System/HomeButton"

//Teardown
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds