//Motorola Shelter Stability Test 18 -- Send an email with no attachment
//Component of Script Series 18
//Completed 6-12-2013

//Setup
run ClassNavigate.ResetState
run ClassScriptConfig.SetContactDataforDeviceA
run ClassScriptConfig.SetContactDataforDeviceB

//Subroutine A2 -- Shelter Device A - Send an email with no attachment to Shelter Device B
wait 10 seconds
run ClassNavigate.OpenApp(Email)
run ClassConfigure.ResetEmail
Log "Composing new email."
Click "Device/Apps/Email/ComposeEmail"
wait 1 second
TypeText universal firstnamedeviceb
wait 1 second
Click (Text:universal fullnamedeviceb)
wait 1 second
run ClassUtilities.ConfirmTextInArea(universal fullnamedeviceb),("10,175"),("450,275")
Click (Text:"Subject")
run ClassUtilities.GenerateRandomNumber
TypeText "Test email no attachment " &universal RandomNumber& "."
run ClassUtilities.ConfirmTextInArea("Test email no attachment"),("10,250"),("450,350")
Click (Text:"Compose email")
run ClassUtilities.GenerateRandomNumber
TypeText "Mr. " &universal firstnamedevicea& " says: " &universal RandomNumber& "."
run ClassUtilities.ConfirmTextInArea(universal RandomNumber),("10,350"),("450,450")
Log "Sending email."
Click "Device/Apps/Email/SendEmail"
wait 1 second
run ClassUtilities.ConfirmTextOnScreen("Inbox")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
run ClassConfigure.UnMuteNotifications
wait 5 seconds

