//Motorola Shelter Stability Test 54 - Open Music Player
//Motorola Shelter Stability Test 55 - Play music file
//Motorola Shelter Stability Test 54 - Close Music Player
//Tests are grouped together due to dependencies in functionality
//Completed 5-20-2013

//Setup
run ClassNavigate.ResetState
run ClassConfigure.MuteMedia

//Test 54 - Open Music Player
run ClassNavigate.OpenApp(Music)

//Test 55 - Play Music File
Click (Text:"Songs")
Click (Text:"Audio Sample 1")
wait 15 seconds

//Test 56 - Exit Music Player
//Script returns to the home screen.  The OS will close the app on its own.  Force closing can be added.
Click "Device/System/HomeButton"

//Teardown
run ClassConfigure.UnMuteMedia
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds

