//Motorola Shelter Stability Test 70 -- Data Stability Uplink - Mobile Hotspot
//Motorola Shelter Stability Test 73 -- Data Stability Downlink - Mobile Hotspot
//Component of Script Series 70
//Completed 6-26-2013

//Setup
run ClassNavigate.ResetState

//Subroutine B1 -- Shelter Device B - Turn off internet connections and connect to Shelter Device A Mobile Hotspot
run ClassNavigate.OpenApp(Settings)
run ClassSettings.SetNetworkData(Off)
run ClassSettings.SetWifi(On)
run ClassNavigate.SettingsOption("Wi-Fi")
run ClassConfigure.ForgetAllWifiConnections
Click "Device/System/Backicon"
wait 1 second
run ClassSettings.ConnectToDefaultHotspot
Click "Device/System/HomeButton"
wait 1 second
Click "Device/Apps/Browser/BrowserIcon"
run ClassConfigure.CloseAllBrowserTabs
run ClassConfigure.SetBrowserHomepageToDefault
run ClassUtilities.ConfirmTextOnScreen("Sign in")
wait 3 seconds
Log "Accessing Wikipedia."
run ClassNavigate.GoToBrowserAddress("wikipedia.org")
wait 2 seconds
run ClassUtilities.ConfirmTextOnScreen("The Free Encyclopedia")
wait 3 seconds
run ClassConfigure.CloseAllBrowserTabs
Click "Device/System/HomeButton"
wait 1 second
run ClassNavigate.OpenApp(Settings)
run ClassSettings.SetNetworkData(On)
run ClassConfigure.ResetWifiToDefault
Click "Device/System/HomeButton"