//Motorola Shelter Stability Test 30 -- Installing an App (Previously: Download a Java application/game)
//Motorola Shelter Stability Test 33 -- Running an App (Previously: Open a downloaded Java Game and then close a Java Game)
//Motorola Shelter Stability Test 35 -- Deleting an App (Previously: Delete a downloaded Java Game)
//Tests are grouped together due to dependencies in functionality
//Completed 6-05-2013
//Current for build 1.25

//Setup
run ClassNavigate.ResetState
run ClassConfigure.UninstallApp(DroidFish)

//Test 30 - Installing an App
Log "Installing test app."
run ClassNavigate.OpenApp(Downloads)
Click (Text:"DroidFish")
run ClassUtilities.ConfirmTextOnScreen("DroidFish")
run ClassUtilities.ConfirmTextOnScreen("Do you want to install")
Click (Text:"Install", SearchRectangle:((10,700),(470,800)))
run ClassUtilities.ConfirmTextOnScreen("App installed")
Log "App installed."

//Test 33 - Running an App
Log "Opening test app."
Click (Text:"Open", SearchRectangle:((10,700),(470,800)))
wait 3 seconds
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Droidfish/ChessBoard")
Click (260,450)
Click (260,350)
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Droidfish/e4")
run ClassUtilities.ConfirmImageOnScreen(ImageName:"Device/Apps/Droidfish/WhitePawnLight",   SearchRectangle:((230,310),(310,385)))
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageNotOnScreen("Device/Apps/Droidfish/e4")
run ClassUtilities.ConfirmImageNotOnScreen(ImageName:"Device/Apps/Droidfish/WhitePawnLight",   SearchRectangle:((230,310),(310,385)))
run ClassNavigate.OpenApp(DroidFish)
wait 3 seconds
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Droidfish/e4")
run ClassUtilities.ConfirmImageOnScreen(ImageName:"Device/Apps/Droidfish/WhitePawnLight", SearchRectangle:((230,310),(310,385)))
Click ("Device/System/MenuButton")
wait 1 second
Click (Text:"New Game")
wait 1 second
Click (Text:"Yes", SearchRectangle:((10,450),(470,550)))
run ClassUtilities.ConfirmImageNotOnScreen("Device/Apps/Droidfish/e4")
run ClassUtilities.ConfirmImageNotOnScreen(ImageName:"Device/Apps/Droidfish/WhitePawnLight",   SearchRectangle:((230,310),(310,385)))
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
Log "Test app runs successfully."

//Test 35 - Deleting an App
run ClassConfigure.UninstallApp(DroidFish)
run ClassNavigate.OpenApp(Downloads)
run ClassUtilities.ConfirmTextOnScreen("DroidFish")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds