//Motorola Shelter Stability Test 04 -- Make a 2G voice call from the call history list
//Requires running of Script Series 01 or 02 first to put a call in the history list
//Component of Script Series 04
//Completed 6-07-2013

//Setup
run ClassNavigate.ResetState

//Subroutine A1 -- Shelter Device A - Set mobile networks to 2G, dial Shelter Device B
run ClassNavigate.OpenApp(Settings)
run ClassNavigate.SettingsOption(More)
Click (Text:"Mobile networks")
run ClassConfigure.Set2Gnetwork(On)
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 3 seconds
Click "Device/AppIcons/TelephoneApp"
Click "Device/Apps/Telephone/HistoryIcon"
Click (Text:"ShelterB")
Click (Text:"Call")
run ClassUtilities.ConfirmTextOnScreen("Dialing")