//Motorola Shelter Stability Test 69 -- Data Stability Uplink - BT (Bluetooth)
//Component of Script Series 69
//Completed 6-26-2013

//Setup
run ClassNavigate.ResetState

//Subroutine A1 -- Shelter Device A - Turn on Bluetooth connection
run ClassNavigate.OpenApp(Settings)
run ClassSettings.SetNetworkData(On)
run ClassSettings.SetWifi(On)
run ClassSettings.SetBluetooth(On)
Click (Text:"Bluetooth")
run ClassConfigure.DeleteBluetoothPairs
wait 1 second
run ClassUtilities.ConfirmTextOnScreen("Bluetooth")
run ClassUtilities.ConfirmTextOnScreen("ON")
Log "Searching for devices."
WaitFor 60, Text:"SEARCH FOR DEVICES"