//Motorola Shelter Stability Test 37 -- Add an appointment in the Calendar
//Motorola Shelter Stability Test 39 -- Delete an appointment in the Calendar
//Tests are grouped together due to dependencies in functionality
//Completed 5-22-2013
//Current for build 1.25

//Setup
run ClassNavigate.ResetState
run ClassConfigure.ResetCalendar(test)

//Test 37 - Add an appointment in the Calendar
run ClassNavigate.OpenApp(Calendar)
run ClassUtilities.ConfirmTextOnScreen("SUN")
run ClassUtilities.ConfirmTextOnScreen("WED")
run ClassUtilities.ConfirmTextOnScreen("SAT")
Log "Calendar open.  Adding test event..."
Click (200,500)
wait 1 second
Click (200,500)
wait 1 second
Click (Text:"Event Name")
wait 1 second
TypeText "Test Event 1"
wait 1 second
Click (Text:"Location")
wait 1 second
TypeText "Office"
wait 2 second
Click "Device/Apps/Calendar/DoneCheckmark"
wait 2 second
run ClassUtilities.ConfirmTextOnScreen("Test")
run ClassUtilities.ConfirmTextOnScreen("Event")
run ClassUtilities.ConfirmTextOnScreen("Office")
Log "Test event added."

//Test 39 - Delete an appointment in the Calendar
Log "Deleting test event."
Click (Text:"Event")
Click "Device/AppIcons/TrashcanIcon"
run ClassUtilities.ConfirmTextOnScreen("Delete this event?")
Click (Text:"OK")
wait 2 seconds
run ClassUtilities.ConfirmTextNotOnScreen("Event")
Log "Test event deleted."

//Teardown
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds
