//Motorola Shelter Stability Test 04 -- Make a 2G voice call from the call history list
//Component of Script Series 04
//Completed 6-07-2013

//Setup
run ClassNavigate.ResetState

//Subroutine A1 -- Shelter Device A - Set mobile networks to 2G, dial Shelter Device B
run ClassNavigate.OpenApp(Settings)
run ClassNavigate.SettingsOption(More)
Click (Text:"Mobile networks")
Click (Text:"Use only 2G")
run ClassUtilities.ConfirmImageOnScreen(ImageName:"Device/Apps/Settings/CheckboxSelected",   SearchRectangle:((25,500),(450,650)))
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 3 seconds
Click "Device/AppIcons/TelephoneApp"
Click "Device/Apps/Telephone/HistoryIcon"
Click (Text:"ShelterB")
Click (Text:"Call")
run ClassUtilities.ConfirmTextOnScreen("Dialing")