//Motorola Shelter Stability Test 02 - Shelter Device A - Make a 3G voice call from the phone book
//Subroutine 1 - Dial Shelter Device B from phone book
//Completed 6-10-2013

//Setup
run ClassNavigate.ResetState

//Test 02A - Make a 3G voice call from the phone book
//Subroutine 1 - Dial Shelter Device B from phone book
Click "Device/AppIcons/TelephoneApp"
Click "Device/Apps/Telephone/ContactsIcon"
Click (Text:"ShelterB")
run ClassUtilities.ConfirmTextOnScreen("Dialing")