//Motorola Shelter Stability Test 58 -- Make a phone call
//Component of Script Series 58
//Completed 6-10-2013

//Setup
run ClassNavigate.ResetState

//Subroutine A1 -- Shelter Device A - Dial Shelter Device B
run ClassScriptConfig.SetContactDataforDeviceA
run ClassScriptConfig.SetContactDataforDeviceB
Click "Device/AppIcons/TelephoneApp"
run ClassNavigate.DialPhoneNumber(universal phonenumberdeviceb)
Click "Device/Apps/Telephone/StartCall"
run ClassUtilities.ConfirmTextOnScreen("Dialing")
run ClassUtilities.ConfirmTextOnScreen(universal firstnamedeviceb)