//Motorola Shelter Stability Test 02 -- Make a 3G voice call from the phone book
//Component of Script Series 02
//Completed 6-10-2013

//Setup
run ClassNavigate.ResetState

//Subroutine A1 -- Shelter Device A - Dial Shelter Device B from phone book
Click "Device/AppIcons/TelephoneApp"
Click "Device/Apps/Telephone/ContactsIcon"
Click (Text:"ShelterB")
run ClassUtilities.ConfirmTextOnScreen("Dialing")