//Motorola Shelter Stability Test 01 -- Make a 2G voice call from the phone book
//Component of Script Series 01
//Completed 6-07-2013

//Setup
run ClassNavigate.ResetState

//Subroutine A1 -- Shelter Device A - Set mobile networks to 2G, dial Shelter Device B
run ClassNavigate.OpenApp(Settings)
run ClassNavigate.SettingsOption(More)
Click (Text:"Mobile networks")
run ClassConfigure.Set2Gnetwork(On)
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 3 seconds
Click "Device/AppIcons/TelephoneApp"
Click "Device/Apps/Telephone/ContactsIcon"
Click (Text:"ShelterB")
run ClassUtilities.ConfirmTextOnScreen("Dialing")
