//Motorola Shelter Stability Test 53 -- Play video streaming content using device browser and video player
//Motorola clarified that test should utilize youtube.com in browser for video streaming.  Video player unnecessary.
//Completed 6-04-2013
//Current for build 1.25

//Setup
run ClassNavigate.ResetState

//Test 53 - Play video streaming content using device browser
run ClassConfigure.MuteMedia
Click "Device/Apps/Browser/BrowserIcon"
run ClassConfigure.CloseAllBrowserTabs
run ClassConfigure.SetBrowserHomepageToDefault
Log "Loading youtube video streaming."
run ClassNavigate.GoToBrowserAddress("m.youtube.com/watch?v=lcJuZIUeBME")
run ClassUtilities.ConfirmTextOnScreen("Canon in D Major")
Click (240,250)
Log "Confirming Youtube video loaded."
WaitFor 60, "Device/Apps/Browser/Sites/YTubeVideoCanonD"
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Browser/Sites/YTubeEmblem")
Log "Confirming video streaming."
wait 60 seconds
Click (240,250)
wait 1 second
run ClassUtilities.ConfirmImageNotOnScreen("Device/Apps/Browser/Sites/YTubeBlackScreenVideo")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Browser/Sites/YTubeProgressBar")
Log "Confirmed video streaming."
run ClassNavigate.GoToBrowserAddress("google.com")
run ClassConfigure.CloseAllBrowserTabs
Click "Device/System/HomeButton"

//Teardown
run ClassConfigure.UnMuteMedia
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds