//Motorola Shelter Stability Test 13 -- Send a MMS with a 1MB image attachment or largest size supported by the device
//Motorola Shelter Stability Test 16 -- Open a MMS with a 1MB image or largest size supported by the device
//Component of Script Series 13
//Completed 6-12-2013

//Setup
run ClassNavigate.ResetState

//Subroutine B1 -- Shelter Device B - Receive Incoming MMS from Shelter Device A and Open Message
//Motorola Shelter Stability Test 16 - Open a MMS with a 1MB image or largest size supported by the device
//Spanish language is used to identify this tested functionality
wait 30 seconds
run ClassUtilities.ConfirmImageOnScreen("Device/System/Taskbar/MessageReceived")
Log "Opening Messaging App."
Click "Device/AppIcons/MessagingApp"
run ClassUtilities.ConfirmTextOnScreen("Messaging")
Click (Text:universal firstnamedevicea)
wait 1 second
ScrollWheelDown 10
wait 1 second
run ClassUtilities.ConfirmTextInArea("El veloz"),("10,490"),("470,730")
run ClassUtilities.ConfirmTextInArea("comia feliz cardillo"),("10,490"),("470,730")
run ClassUtilities.ConfirmImageOnScreen(ImageName:"Device/Apps/Messaging/ImageAttachmentSample1c",   SearchRectangle:((5,400),(470,700)))
run ClassUtilities.ConfirmTextInArea("Attachment"),("10,490"),("470,730")
run ClassUtilities.ConfirmTextInArea("jpg"),("10,490"),("470,730")
Log "Text message received."
Click "Device/System/BackIcon"
wait 1 second
run ClassUtilities.ConfirmTextOnScreen("Messaging")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
run ClassUtilities.ConfirmImageNotOnScreen("Device/System/Taskbar/MessageReceived")
wait 5 seconds