//Motorola Shelter Stability Test 01 - Make a 2G voice call from the phone book
//Motorola Shelter Stability Test 07 - Receive a voice call
//Component of Script Series 01
//Completed 6-07-2013

//Subroutine B1 - Shelter Device B - Receive Incoming Call from Shelter Device A
//Motorola Shelter Stability Test 07 - Receive a voice call
run ClassUtilities.ConfirmTextOnScreen("INCOMING CALL")
run ClassUtilities.ConfirmTextOnScreen("SHELTERA")
run ClassUtilities.ConfirmTextOnScreen("MOBILE")
run ClassNavigate.AnswerCall
run ClassUtilities.ConfirmTextOnScreen("SHELTERA")
run ClassUtilities.ConfirmTextOnScreen("MOBILE")
Click "Device/Apps/Telephone/EndCall"
run ClassUtilities.ConfirmImageNotOnScreen("Device/Apps/Telephone/EndCall")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/HistoryIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/PhoneIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/ContactsIcon")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds