//Motorola Shelter Stability Test 10 -- Send an SMS maximum number of characters with out requiring the message to be segmented
//Component of Script Series 10
//Completed 6-11-2013

run ClassScriptConfig.SetContactDataforDeviceA
run ClassScriptConfig.SetContactDataforDeviceB

//Subroutine A2 -- Shelter Device A - Send max characters SMS to Shelter Device B
//English language is used to identify this tested functionality
Click "Device/AppIcons/MessagingApp"
run ClassUtilities.IfImageOnScreen("Device/Apps/Messaging/BackToMessaging"),("Device/Apps/Messaging/BackToMessaging")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Messaging/MessagingAppHeader")
Click "Device/Apps/Messaging/NewMessageIcon"
wait 1 second
run ClassUtilities.ConfirmTextOnScreen("New message")
Log "Creating new text message."
Click (Text:"To")
wait 1 second
TypeText universal firstnamedeviceb
wait 1 second
Click (Text:universal fullnamedeviceb)
run ClassUtilities.ConfirmTextInArea(universal fullnamedeviceb),("10,100"),("450,200")
run ClassConfigure.ResetMessaging
Click "Device/Apps/Messaging/TextFieldEmpty"
wait 1 second
Log "Adding text."
TypeText "The quick brown fox jumped over the lazy dog. "
wait 2 seconds
TypeText "The quick brown fox jumped over the lazy dog. "
wait 2 seconds
TypeText "The quick brown fox jumped over the lazy dog. "
wait 2 seconds
TypeText "The quick brown fox ju"
wait 3 seconds
run ClassUtilities.ConfirmTextInArea("quick brown fox"),("10,315"),("470,425")
run ClassUtilities.ConfirmTextInArea("jumped over the lazy dog"),("10,315"),("470,425")
run ClassUtilities.ConfirmTextInArea("0"),("390,315"),("470,365")
run ClassUtilities.ConfirmTextNotInArea("/ 2"),("390,315"),("470,365")
Log "Sending message."
Click "Device/Apps/Messaging/SendMessage"
wait 3 seconds
Click "Device/System/BackIcon"
Click (Text:universal fullnamedeviceb)
ScrollWheelDown 3
run ClassUtilities.ConfirmTextInArea("quick brown fox"),("10,475"),("470,750")
run ClassUtilities.ConfirmTextInArea("jumped over the lazy dog"),("10,475"),("470,750")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Messaging/TextFieldEmpty")
Log "Text message sent."
Click "Device/System/BackIcon"
wait 1 second
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Messaging/MessagingAppHeader")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
run ClassConfigure.UnMuteNotifications
wait 5 seconds