//Motorola Shelter Stability Test 64 -- Menu Navigation
//Completed 5-30-2013
//Current for build 1.25

//Setup
run ClassNavigate.ResetState

//Test 64 - Menu Navigation
run ClassNavigate.OpenApp(Settings)
run ClassNavigate.SettingsOption("About Phone")
Click (Text:"Status")
run ClassUtilities.ConfirmTextOnScreen("Battery status")
run ClassUtilities.ConfirmTextOnScreen("Battery level")
Click "Device/System/BackIcon"
Click (Text:"Legal information")
Click (Text:"Open source licenses")
wait 5 seconds
run ClassUtilities.ConfirmTextOnScreen("Open source licenses")
run ClassUtilities.ConfirmTextOnScreen("kernel")
run ClassUtilities.ConfirmTextOnScreen("root")
run ClassUtilities.ConfirmTextOnScreen("apk")
Click (Text:"kernel")
run ClassUtilities.ConfirmTextOnScreen("Notices")
Click "Device/System/HomeButton"
wait 1 second
run ClassUtilities.ConfirmTextNotOnScreen("Open source licenses")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds