//Motorola Shelter Stability Test 65 - Turn the WiFi radio off and on
//Motorola Shelter Stability Test 66 - Connect/Disconnect to a WiFi network
//Tests are grouped together due to dependencies in functionality
//Completed 6-05-2013

//Setup
run ClassNavigate.UnlockDevice

//Test 65 - Turn the WiFi radio off and on
run ClassNavigate.OpenTaskbar
Click (Text:"USB connected")

//Teardown
Click "Device/System/HomeButton"
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds