//Motorola Shelter Stability Test 05 -- Make a 3G voice call from the call history list
//Component of Script Series 05
//Completed 6-10-2013

//Subroutine B1 -- Shelter Device B - Receive Incoming Call from Shelter Device A
run ClassUtilities.ConfirmTextOnScreen("INCOMING CALL")
run ClassUtilities.ConfirmTextOnScreen("SHELTERA")
run ClassUtilities.ConfirmTextOnScreen("MOBILE")
run ClassNavigate.AnswerCall
run ClassUtilities.ConfirmTextOnScreen("SHELTERA")
run ClassUtilities.ConfirmTextOnScreen("MOBILE")
Click "Device/Apps/Telephone/EndCall"
run ClassUtilities.ConfirmImageNotOnScreen("Device/Apps/Telephone/EndCall")
Click "Device/AppIcons/TelephoneApp"
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/HistoryIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/PhoneIcon")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Telephone/ContactsIcon")
Click "Device/Apps/Telephone/HistoryIcon"
run ClassUtilities.ConfirmTextInArea("ShelterA"),("10,100"),("450,225")
run ClassUtilities.ConfirmImageOnScreen(ImageName:"Device/Apps/Telephone/0MinsAgo",   SearchRectangle:((10,100),(450,225)))
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
wait 5 seconds