//Motorola Shelter Stability Test 10 -- Send an SMS maximum number of characters with out requiring the message to be segmented
//Motorola Shelter Stability Test 17 -- Open a SMS
//Component of Script Series 10
//Completed 6-11-2013

//Subroutine B1 -- Shelter Device B - Receive Incoming SMS from Shelter Device A and Open Message
//Motorola Shelter Stability Test 17 - Open a SMS
//English language is used to identify this tested functionality
wait 30 seconds
run ClassUtilities.ConfirmImageOnScreen("Device/System/Taskbar/MessageReceived")
Log "Opening Messaging App."
Click "Device/AppIcons/MessagingApp"
run ClassUtilities.IfImageOnScreen("Device/Apps/Messaging/BackToMessaging"),("Device/Apps/Messaging/BackToMessaging")
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Messaging/MessagingAppHeader")
Click (Text:universal firstnamedevicea)
wait 1 second
ScrollWheelDown 10
wait 1 second
run ClassUtilities.ConfirmTextInArea("The quick brown fox jumped"),("10,450"),("470,730")
run ClassUtilities.ConfirmTextInArea("jumped over the lazy dog"),("10,450"),("470,730")
Log "Text message received."
Click "Device/System/BackIcon"
wait 1 second
run ClassUtilities.ConfirmImageOnScreen("Device/Apps/Messaging/MessagingAppHeader")
Click "Device/System/HomeButton"

//Teardown
run ClassUtilities.ConfirmImageOnScreen("Device/System/AppsIcon")
run ClassUtilities.ConfirmImageNotOnScreen("Device/System/Taskbar/MessageReceived")
run ClassConfigure.UnMuteNotifications
wait 5 seconds