//Motorola Shelter Stability Test 13 -- Send a MMS with a 1MB image attachment or largest size supported by the device
//Motorola Shelter Stability Test 16 -- Open a MMS with a 1MB image or largest size supported by the device
//Component of Script Series 13
//Completed 6-12-2013

//Subroutine B1 -- Shelter Device B - Setup
run ClassNavigate.ResetState
run ClassConfigure.MuteNotifications
run ClassConfigure.ResetMessagingApp